name: "TypeScript Build and Lint"
description: "Install deps, build, env setup for TypeScript projects and run code analysis with Eslint and Prettier"

inputs:
  working-directory:
    description: "Path to TypeScript project directory"
    required: false
    default: "."

  version:
    description: "Version of PNPM to use (e.g., 10)"
    required: false
    default: "10"

  eslint-fail-on-error:
    description: "Whether to fail the action if ESLint finds errors (true/false)"
    required: false
    default: "false"

  eslint-fail-on-warning:
    description: "Whether to fail the action if ESLint finds warnings (true/false)"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Build and Setup Environment
      uses: intellegens-hr/actions/.github/actions/ts-build@master
      with:
        working-directory: ${{ inputs.working-directory }}
        version: ${{ inputs.version }}

    - name: Run Code Analysis
      uses: intellegens-hr/actions/.github/actions/ts-eslint@master
      with:
        working-directory: ${{ inputs.working-directory }}
        fail-on-error: ${{ inputs.eslint-fail-on-error }}
        fail-on-warning: ${{ inputs.eslint-fail-on-warning }}

    - name: Run Prettier
      uses: intellegens-hr/actions/.github/actions/ts-prettier@master
      with:
        working-directory: ${{ inputs.working-directory }}
