name: "TypeScript Build and Lint"
description: "Install deps, build, env setup for TypeScript projects and run code analysis with Eslint and Prettier"

inputs:
  working-directory:
    description: "Path to TypeScript project directory"
    required: false
    default: "./"

  version:
    description: "Version of PNPM to use (e.g., 10)"
    required: false
    default: "10"

  eslint-fail-on-error:
    description: "Whether to fail the action if ESLint finds errors (true/false)"
    required: false
    default: "false"

  prettier-fail-on-error:
    description: "Whether to fail the action if Prettier finds formatting issues (true/false)"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Build and Setup Environment
      uses: intellegens-hr/actions/.github/actions/ts-build@master
      with:
        working-directory: ${{ inputs.working-directory }}
        version: ${{ inputs.version }}

    - name: Run Code Analysis
      uses: intellegens-hr/actions/.github/actions/ts-eslint@master
      with:
        working-directory: ${{ inputs.working-directory }}
        fail-on-error: ${{ inputs.eslint-fail-on-error }}

    - name: Run Prettier
      uses: intellegens-hr/actions/.github/actions/ts-prettier@master
      with:
        working-directory: ${{ inputs.working-directory }}
        fail-on-error: ${{ inputs.prettier-fail-on-error }}
