name: "Run Prettier for TypeScript projects"
description: "Run Prettier for TypeScript projects"

inputs:
  working-directory:
    description: "Path to TypeScript project directory"
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: Run Prettier
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: npm exec prettier --check .
