name: "Run Eslint for TypeScript projects"
description: "Run Eslint and output results in JSON format for TypeScript projects"

inputs:
  working-directory:
    description: "Path to TypeScript project directory (e.g., ./report)"
    required: false
    default: "."

  report-name:
    description: "Full report name with extension (e.g., 'eslint_report.json')"
    required: false
    default: "eslint_report.json"

  fail-on-error:
    description: "Whether to fail the action if ESLint finds errors (true/false)"
    required: false
    default: "false"

  fail-on-warning:
    description: "Whether to fail the action if ESLint finds warnings (true/false)"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Run Eslint
      working-directory: ${{ inputs.working-directory }}
      run: |
        if [ "${{ inputs.fail-on-error }}" = "true" ]; then
          npm exec eslint -- "**/*.{ts,tsx}" --output-file "${{ inputs.report-name }}" --format json
        else
          npm exec eslint -- "**/*.{ts,tsx}" --output-file "${{ inputs.report-name }}" --format json || true
        fi
      shell: bash

    - name: Create Full ESLint Report And Annotate Results
      if: always()
      uses: intellegens-hr/actions/bin/actions/eslint-json-md@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        report-path: ${{ inputs.working-directory }}/${{ inputs.report-name }}
        fail-on-error: ${{ inputs.fail-on-error == 'true' }}
        fail-on-warning: ${{ inputs.fail-on-warning == 'true' }}
